XTB 6.4.1 -> 6.5.1
markuskowa/NixOS-QChem pull request #202
Opened 2022-07-18 13:09 UTC by sheepforce

Update to the most recent XTB version with many new features and bugfixes. XTB now requires 2 new dependencies:

- mctc-lib to unify input file parsing between different Grimme group programs. mctc-lib requires
  - json-fortran to parse QCSchema input files
- test-drive to automate fortran tests in XTB

2022-07-19 08:57 UTC, markuskowa requested changes

2022-07-19 08:57 UTC, markuskowa commented on result
> +/nix/store/zbzscwa6c858nmxpb8kiqgf4v12bhmam-test-drive-0.4.0
Oops.

2022-07-19 11:10 UTC, markuskowa commented
This seems to break pysisyphus:
```
FAILED tests/test_afir/test_afir.py::test_three_frag_afir - assert 2.62350526...
FAILED tests/test_modekill/test_modekill.py::test_modekill_xtb - AssertionErr...
FAILED tests/test_xtb/test_xtb.py::test_xtb_forces - assert 9.236406978009484...
= 3 failed, 678 passed, 190 skipped, 325 deselected, 10 xfailed, 62 warnings in 2622.60s (0:43:42) =

          ==================== Thresholds ====================
          CN  :   150.00000
          rep :   500.00000
          disp:  2500.00000
          HB1 :   250.00000
          HB2 :   450.00000

          Pauling EN used:
          Z : 1  EN :  2.20
          Z : 8  EN :  3.44
          electric field strengths (au): 0.000

           ------------------------------------------------- 
          |           Force Field Initialization            |
           ------------------------------------------------- 

          distances ...
          ----------------------------------------
          generating topology and atomic info file ...
          pair mat ...
          computing topology distances matrix with Floyd-Warshall algo ...
          making topology EEQ charges ...
          #fragments for EEQ constrain: 1
          ----------------------------------------
          generating topology and atomic info file ...
          pair mat ...
          computing topology distances matrix with Floyd-Warshall algo ...
          making topology EEQ charges ...
          #fragments for EEQ constrain: 1
          rings ...
          # BATM   0
          # H in HB   2

  atom   neighbors  erfCN metchar sp-hybrid imet pi  qest     coordinates
    1  O       2    1.92   0.00         3    0    0  -0.571   -0.000000   -0.209404    0.000000
    2  H       1    0.97   0.00         0    0    0   0.285    1.481500    0.837616    0.000000
    3  H       1    0.97   0.00         0    0    0   0.285   -1.481500    0.837616    0.000000

          #atoms :   3
          #bonds :   2
          #angl  :   1
          #tors  :   0
          #nmol  :   1
          #optfrag :   1

          ==================== Thresholds ====================
          CN  :   150.00000
          rep :   500.00000
          disp:  2500.00000
          HB1 :   250.00000
          HB2 :   450.00000

          Pauling EN used:
          Z : 1  EN :  2.20
          Z : 8  EN :  3.44
          electric field strengths (au): 0.000

           ------------------------------------------------- 
          |           Force Field Initialization            |
           ------------------------------------------------- 

          distances ...
          ----------------------------------------
          generating topology and atomic info file ...
          pair mat ...
          computing topology distances matrix with Floyd-Warshall algo ...
          making topology EEQ charges ...
          #fragments for EEQ constrain: 1
          ----------------------------------------
          generating topology and atomic info file ...
          pair mat ...
          computing topology distances matrix with Floyd-Warshall algo ...
          making topology EEQ charges ...
          #fragments for EEQ constrain: 1
          rings ...
          # BATM   0
          # H in HB   2

  atom   neighbors  erfCN metchar sp-hybrid imet pi  qest     coordinates
    1  O       2    1.92   0.00         3    0    0  -0.571   -0.000000   -0.209404    0.000000
    2  H       1    0.97   0.00         0    0    0   0.285    1.481500    0.837616    0.000000
    3  H       1    0.97   0.00         0    0    0   0.285   -1.481500    0.837616    0.000000

          #atoms :   3
          #bonds :   2
          #angl  :   1
          #tors  :   0
          #nmol  :   1
          #optfrag :   1
```

2022-07-19 12:21 UTC, sheepforce commented
@eljost this is most likely also a problem for upstream pysisyphus. Could you check if pysis needs to be tweaked for XTB 6.5. They've changed topology handling in GFN-FF.

2022-08-24 09:15 UTC, sheepforce commented
This commit https://github.com/eljost/pysisyphus/commit/e382c9dec9cc5bf4755414ea647a649322168bdb fixes pysisyphus it. I will include it as soon as it reaches master.

2022-09-26 08:42 UTC, markuskowa commented
Is this fixed now in pysisyphus?

2022-09-26 14:01 UTC, sheepforce commented
Yes, as part of this large merge commit to master: https://github.com/eljost/pysisyphus/commit/1b73e5dd167ce63a6ea9337544b73ad753467558
May be better to use a pin of master there for the moment than to build Frankenstein's patch.

2022-09-28 15:41 UTC, markuskowa commented
pysisyphus still fails with the same error.

2022-10-06 12:49 UTC, sheepforce commented
> I still see the same error.

Yes, yes. But now the upstream CMake update also broke mctc-lib and test-drive. I have first fixed those. I am currently sitting down with @eljost and we are working through the failing tests. They are mostly numerical noise. I will ping you when done.

2022-10-07 09:25 UTC, sheepforce commented
Now this has finally worked. Should be ready now.

2022-10-07 11:28 UTC, merged